openapi: 3.0.0
info:
  title: pocket4cut web1 API docs
  description: pocket4cut web1팀의 API 문서입니다
  version: 0.1.9
servers:
  - url: https://port-0-pocket4cut-m0vc6i8ed9c19e71.sel4.cloudtype.app/
    description: pocket4cut
paths:
  /api/user/{user_id}:
    $ref: './user.yaml'
  /api/review/{user_id}:
    $ref: './review.yaml'