openapi: 3.0.0
info:
  title: pocket4cut web1 API docs
  description: pocket4cut web1팀의 API 문서입니다
  version: 0.1.9
servers:
  - url: https://port-0-langbot-backend-m22m0z85debbab55.sel4.cloudtype.app
    description: pocket4cut
paths:
  /api/user/{user_id}:
    $ref: './user.yaml'
  /api/user/{user_id}/booth-visit:
    $ref: './booth-visit.yaml'
  /api/review/user/{user_id}:
    $ref: './review-user.yaml'
  /api/review/mypage/{user_id}:
    $ref: './review-mypage.yaml'
  /api/review/{review_id}:
    $ref: './review.yaml'
  /api/review/booth/{photobooth_id}:
    $ref: './review-booth.yaml'
  /api/review/boothphoto/{photobooth_id}:
    $ref: './review-boothphoto.yaml'
  /api/map:
    $ref: './map.yaml'
  /api/map/search:
    $ref: './map-search.yaml'
  /api/album/{user_id}:
    $ref: './album.yaml'
  /api/photo/like/{photo_id}:
    $ref: './photo-like.yaml'
  /api/photo/{photo_id}:
      $ref: './get-photo.yaml'
  