name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: sooieese/project-team-web-be11
          stage: main
          yaml: |
            name: pocket4cut
            app: node@20
            options:
              ports: "3000"
              install: npm install
              start: npm start
              env:
                - name: KAKAO_ID
                  secret: kakaosecret
                - name: COOKIE_SECRET
                  secret: cookiesecret
                - name: PORT
                  value: "3000"
                - name: JWT_SECRET
                  secret: jwtsecret
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}