name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: sooieese/project-team-web-be11
          stage: main
          yaml: |
            name: pocket4cut
            app: node@20
            options:
              ports: "3000"
              install: npm install
              start: npm start
              env:
                - name: KAKAO_ID
                  secret: KAKAO_ID
                - name: COOKIE_SECRET
                  secret: COOKIE_SECRET
                - name: PORT
                  value: "3000"
                - name: JWT_SECRET
                  secret: JWT_SECRET
                - name: DB_HOST
                  secret: DB_HOST
                - name: DB_NAME
                  secret: DB_NAME
                - name: DB_USER
                  secret: DB_USER
                - name: DB_PASSWORD
                  secret: DB_PASSWORD
                - name: DB_PORT
                  secret: DB_PORT
                - name: S3_ACCESS_KEY_ID
                  secret: S3_ACCESS_KEY_ID
                - name: S3_SECRET_ACCESS_KEY
                  secret: S3_SECRET_ACCESS_KEY
                - name: S3_BUCKET_NAME
                  secret: S3_BUCKET_NAME
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}